name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., 1.2.3 or v1.2.3)"
        required: true
      prerelease:
        description: "Mark release as prerelease"
        type: boolean
        required: false
        default: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build with Vite
        run: npm run build

      - name: Verify build output
        run: |
          echo "Build output verification:"
          ls -la dist/
          echo ""
          echo "Checking bundle sizes:"
          du -h dist/*.mjs dist/*.umd.js
          echo ""
          echo "Checking that main.mjs contains utilities:"
          grep -c "export" dist/main.mjs || echo "No exports found in main.mjs"
          echo ""
          echo "Checking that webskel.mjs contains main class:"
          grep -c "export" dist/webskel.mjs || echo "No exports found in webskel.mjs"

      - name: Copy bundles to releases folder
        run: |
          mkdir -p releases
          cp -f dist/webskel.mjs releases/webskel.mjs
          cp -f dist/webskel.umd.js releases/webskel.umd.js
          cp -f dist/main.mjs releases/main.mjs
          cp -f dist/main.umd.js releases/main.umd.js
          echo "Bundles copied to releases folder:"
          ls -la releases/

      - name: Show git status
        run: git status

      - name: Commit bundles into repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add releases/ dist/
          if git diff --cached --quiet; then
            echo "No bundle changes to commit"
          else
            echo "Committing bundles into releases/"
            git commit -m "chore(release): add Vite bundles for ${{ github.event.inputs.version }}"
            git push origin HEAD:${{ github.event.repository.default_branch }}
          fi

      - name: Compute tag name
        id: tag
        run: |
          VERSION='${{ github.event.inputs.version }}'
          if [[ "$VERSION" =~ ^v ]]; then TAG="$VERSION"; else TAG="v$VERSION"; fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ github.event.inputs.version }}
          body: |
            ## WebSkel ${{ github.event.inputs.version }}
            
            ### Bundle Files
            - `webskel.mjs` - Main WebSkel class (ES Module)
            - `webskel.umd.js` - Main WebSkel class (UMD)
            - `main.mjs` - All utilities and main class (ES Module)
            - `main.umd.js` - All utilities and main class (UMD)
            
            ### Import Examples
            ```javascript
            // Import everything
            import { sanitize, getBrowser, WebSkel } from 'webskel';
            
            // Import main class only
            import { WebSkel } from 'webskel/webskel';
            
            // Import specific utilities
            import { sanitize } from 'webskel/dom-utils';
            import { showModal } from 'webskel/modal-utils';
            ```
            
            ### Features
            - ✅ Tree-shaking friendly imports
            - ✅ Individual utility exports
            - ✅ ES Module and UMD support
            - ✅ Optimized bundle sizes
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
          files: |
            releases/webskel.mjs
            releases/webskel.umd.js
            releases/main.mjs
            releases/main.umd.js
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

