name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release (e.g., 1.2.3 or v1.2.3)"
        required: true
      prerelease:
        description: "Mark release as prerelease"
        type: boolean
        required: false
        default: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.repository.default_branch }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Copy .mjs files to releases folder
        run: |
          mkdir -p releases
          if compgen -G "dist/**/*.mjs" > /dev/null; then
            find dist -type f -name "*.mjs" -exec cp -f --parents {} releases/ \;
          elif compgen -G "dist/*.mjs" > /dev/null; then
            cp -f dist/*.mjs releases/
          else
            echo "No .mjs files found in dist"
          fi

      - name: Commit .mjs files into repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add releases/
          if git diff --cached --quiet; then
            echo "No .mjs changes to commit"
          else
            echo "Committing .mjs files into releases/"
            git commit -m "chore(release): add .mjs files for ${{ github.event.inputs.version }}"
            git push origin HEAD:${{ github.event.repository.default_branch }}
          fi

      - name: Compute tag name
        id: tag
        run: |
          VERSION='${{ github.event.inputs.version }}'
          if [[ "$VERSION" =~ ^v ]]; then TAG="$VERSION"; else TAG="v$VERSION"; fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


