name: Release

on:
  push:
    tags:
      - 'v*'
      - 'V*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Archive dist
        run: |
          tar -czf webskel-dist-${{ github.ref_name }}.tar.gz dist
          zip -r webskel-dist-${{ github.ref_name }}.zip dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**
            webskel-dist-${{ github.ref_name }}.tar.gz
            webskel-dist-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
