name: Release Please

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          token: ${{ secrets.GIT_TOKEN }}
      - name: Log release info
        if: steps.release.outputs.release_created == 'true'
        run: |
          echo "Release created: ${{ steps.release.outputs.tag_name }}"


